### ISSUE TITLE
Plotting Series values 

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-musclehub#1]
https://github.com/yuunaK/intro-data-capstone-musclehub/blob/4837210631287af60e240ac22985f29645125b07/Yuuna_Mathew_Capstone_Project_MuscleHub_AB_Test/musclehub.py#L194

Code works great. It gets the job done. A small tip: in general passing the series values makes more sense than passing the whole series. So you could do:
plt.pie(ab_counts.first_name.values, labels=['Group A (Fitness Test)', 'Group B (No Fitness Test)'], autopct="%0.2f%%" ) 

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.values.html

**Comment by yuunaK** [comment]
Thank you again for a very valuable clarification.  Thank you for pointing out the difference between passing a series values as opposed to an entire series again makes sense.  I had a question regarding this point and your comment is very helpful. Thank you.
