### ISSUE TITLE
subplot first then plot

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-musclehub#2]
https://github.com/yuunaK/intro-data-capstone-musclehub/blob/4837210631287af60e240ac22985f29645125b07/Yuuna_Mathew_Capstone_Project_MuscleHub_AB_Test/musclehub.py#L381-L382

When you call plt.bar, plt.plot etc., it creates the axis objects by default. One can access the default axis by ax=plt.gca(). In your code you create the bar plot which would have created the axis. On next line you are recreating another ax object from plt.subplot(). It considers as a bug. In Matplotlib you will get a warning like:
"MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance."

So the fix is, first create the ax object. Then plot.
ax = plt.subplot() 
plt.bar(range(len(app_pivot)), app_pivot['Percent With Application'].values)

**Comment by yuunaK** [comment]
Thank you for this clarification regarding when to create the axis object.  I will make the axis object before creating the graph or plot.  I think I was confusing plt.show() as the creation of graph.
