### ISSUE TITLE
Increase yaxis range

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-musclehub#3]
https://github.com/yuunaK/intro-data-capstone-musclehub/blob/4837210631287af60e240ac22985f29645125b07/Yuuna_Mathew_Capstone_Project_MuscleHub_AB_Test/musclehub.py#L413-L414

From the final_member_pivot table you can see the max percentage is 10%. So I would increase the y axis range to 15 or 20% to have a better readability.

**Comment by yuunaK** [comment]
Thank you for this suggestion.  This makes sense as well.  I will edit this statement as you suggest..
